default: &default

  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: edgeschool_development

test:
  <<: *default
  database: edgeschool_test


production:
  <<: *default
  database: edgeschool_production
  username: edgeschool
  password: <%= ENV['EDGESCHOOL_DATABASE_PASSWORD'] %>
